config/routes.rb
IssueMap::Application.routes.draw do
  resources :maps do
    new do
      post :preprocess
    end
  end
  match "/map_cache/:id", :to => "maps#cache", :as => :map_cache

  match "/proxy/(*path)", :to => "proxy#proxy", :as => :geoiq_proxy
  match "/pages/:action", :to => "pages", :as => :page
  root :to => "pages#home"

  match "/fitter_happier(/:action)", :to => "fitter_happier", :action => :index
end

app/models/map.rb
class Map < ActiveRecord::Base
  attr_accessor :extent
  attr_accessor :color_palette
  attr_accessor :flip_colors

  validates_presence_of :title, :original_csv_data
  validates_presence_of :location_column_name, :location_column_type
  validates_presence_of :data_column_name, :data_column_type

  before_create :set_token, :set_admin_token

  def provider
    "Acetate" # "OpenStreetMap (Road)"  "Yahoo Road", "Google Hybrid", "Google Terrain"
  end

  def flip_colors?
    flip_colors.present?
  end

  def to_param
    slug = title.gsub(/\W/, " ").strip.gsub(/\s+/, "-").downcase if title
    [token, slug].compact.join("-")
  end

  def dom_token
    ["map", (token || "new")].join("_")
  end

  # options - The Hash of options used to refine the PNG
  #           :text - overlayed text on the map (default: token)
  #           :size - s, m, or l (default: l)
  def to_png(options = {})
    text = options.delete(:text) || token
    size = options.delete(:size) || "l"
    to_map_format("png", :text => text, :size => size)
  end

  def to_csv
    to_dataset_format("csv")
  end

  def to_kml
    to_dataset_format("kml")
  end

  protected

  def to_map_format(format, options = {})
    query = options.merge(:format => format)
    GeoIQ.get("/maps/#{self.geoiq_map_xid}", :query => query).body
  end

  def to_dataset_format(format)
    GeoIQ.get("/datasets/#{self.geoiq_dataset_xid}.#{format}").body
  end

  def generate_token(size = 12)
    begin
      token = ActiveSupport::SecureRandom.hex(size).first(size)
    end while self.class.find_by_token(token)
    token
  end

  def set_token
    self.token = generate_token(6) if token.blank?
  end

  def set_admin_token
    self.admin_token = generate_token(12) if admin_token.blank?
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_filter :find_map, :only => [:show, :update, :cache, :update]
  before_filter :check_admin_token, :only => :show
  before_filter :ensure_admin_token, :only => :update
  before_filter :ensure_correct_slug, :only => :show
  caches_page :cache

  def new
    @map = Map.new(params[:map])
  end

  def preprocess
    import = DatasetPreprocessor.new(params[:data])
    import.check_validity!
    render :text => import.to_json
  rescue StandardError => e
    logger.error(error_message_and_backtrace(e))
    render :text => { :error => e.message }.to_json, :status => :internal_server_error
  end

  def create
    @map = Map.new(params[:map])
    if @map.save
      add_map_to_owned_map_list(@map)
      redirect_to @map
    else
      render :new
    end
  rescue StandardError => e
    logger.error(error_message_and_backtrace(e))
    flash.now[:error] = "Your map could not be saved! Please try again"
    render :new
  end

  def update
    if @map.update_attributes(params[:map])
      expire_page :action => :cache, :id => @map.token, :format => "png"
    end
    redirect_to @map
  end

  def show
    respond_to do |format|
      format.html {}
      format.csv { send_map_data(@map.to_csv, :csv, "csv") }
      format.kml { send_map_data(@map.to_kml, :kml, "kml") }
      format.png { send_map_data(@map.to_png(:text => map_url(@map.token), :size => params[:size]), :png, "png") }
    end
  end

  def cache
    # we can only cache one png size unless we make custom routes
    params[:size] = "m"
    show
  end

  protected

  def add_map_to_owned_map_list(map)
    map_ids = session[:owned_maps] || []
    map_ids.push(map.id)
    map_ids.shift([0, map_ids.length - 10].max)
    session[:owned_maps] = map_ids
  end

  def send_map_data(bytes, type, format)
    send_data(bytes, :type => type, :filename => "#{@map.to_param}.#{format}", :disposition => "inline")
  end

  def find_map
    token = params[:id].split("-").first if params[:id]
    @map = Map.find_by_token(token)
    raise ActiveRecord::RecordNotFound, "No Maps matches that token" unless @map
  end

  def check_admin_token
    admin_token = params.delete(:admin_token)
    return unless admin_token && format_html?
    add_map_to_owned_map_list(@map) if admin_token == @map.admin_token
    redirect_to params
  end

  def ensure_admin_token
    unless map_admin?(@map)
      render :text => "Unauthorized.", :status => :unauthorized
    end
  end

  def ensure_correct_slug
    return unless format_html?
    redirect_to(@map, :status => :moved_permanently) unless params[:id] == @map.to_param
  end

  def format_html?
    params[:format].blank? || params[:format].to_s == "html"
  end

  def map_admin?(map)
    session[:owned_maps].include?(map.id) if session[:owned_maps]
  end
end

app/helpers/maps_helper.rb
module MapsHelper
  def fieldset_error_messages(object, *methods)
    messages = methods.map do |method|
      error_message  = object.errors[method]
      error_sentence = [object.class.human_attribute_name(method), error_message].join(" ")
      content_tag(:div, error_sentence) if error_message.present?
    end.join
    content_tag(:div, messages, :class => "error-message")
  end

  def fieldset_errored?(object, *methods)
    methods.any? { |method| object.errors[method].present? }
  end

  def fieldset_completed?(object, *methods)
    methods.all? { |method| object.errors[method].blank? && object.send(method).present? }
  end

  def fieldset_style_classes(object, *methods)
    errored   = "errored"   if fieldset_errored?(object, *methods)
    completed = "completed" if fieldset_completed?(object, *methods)
    [errored, completed].compact.join(" ")
  end

  def completable_fieldset(object, *methods, &block)
    options = methods.extract_options!
    style_class = options.delete(:class)
    additional_classes = fieldset_style_classes(object, *methods)
    content = fieldset_error_messages(object, *methods)
    content << capture(&block)
    content_tag(:fieldset, content, options.merge(:class => "#{style_class} #{additional_classes}"))
  end

  def compact_embed_code(map, locals = {})
    embed_code = render :partial => "maps/embed", :locals => locals.merge(:map => map)
    CGI::unescape_html(embed_code.lines.map(&:strip).join)
  end

  def location_type_options
    [["Please select a location type...", nil]] + AppConfig[:boundaries]
  end

  def data_type_options
    [["Please select a data type...", nil]] + DATA_TYPES
  end

  DATA_TYPES = [['Plain text', 'string'],
                ['Whole numbers', 'integer'],
                ['Decimals', 'decimal'],
                ['Time or Date', 'datetime']]

  def clippy(text, bgcolor='#FFFFFF')
    html = <<-EOF.html_safe
      <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
              width="110"
              height="14"
              id="clippy" >
      <param name="movie" value="/flash/clippy.swf"/>
      <param name="allowScriptAccess" value="always" />
      <param name="quality" value="high" />
      <param name="scale" value="noscale" />
      <param NAME="FlashVars" value="text=#{h(text)}">
      <param name="bgcolor" value="#{bgcolor}">
      <embed src="/flash/clippy.swf"
             width="110"
             height="14"
             name="clippy"
             quality="high"
             allowScriptAccess="always"
             type="application/x-shockwave-flash"
             pluginspage="http://www.macromedia.com/go/getflashplayer"
             FlashVars="text=#{h(text)}"
             bgcolor="#{bgcolor}"
      />
      </object>
    EOF
  end

  def map_admin?(map)
    session[:owned_maps].include?(map.id) if session[:owned_maps]
  end

  def map_admin_section(map, &block)
    capture(&block) if map_admin?(map)
  end
end

app/views/maps/_add_this.html.haml
.addthis_toolbox.addthis_default_style
  -# = link_to "Share", "http://www.addthis.com/bookmark.php?v=250&amp;username=issuemap", :class => "addthis_button_compact"
  -# %span.addthis_separator= "|"
  %a.addthis_button_twitter
  %a.addthis_button_facebook
  %a.addthis_button_email

= javascript_tag do
  :plain
    var addthis_config = { "data_track_clickback": true };
= javascript_include_tag "http://s7.addthis.com/js/250/addthis_widget.js#username=issuemap"

app/views/maps/_color_palette.html.haml
%table.palette{ "data-palette-name" => name, "data-palette-colors" => colors.to_json, :class => name }
  - colors.each do |color|
    - hex_color = "#%06x" % color
    %tr
      %td.color{ :style => "background-color: #{hex_color}" }

app/views/maps/_color_palettes.html.haml
%h3
  = link_to "Flip", "#", :class => "flip-colors"
  Colors
.white
  - MapStyles::WHITE_PALETTES.each do |name, colors|
    = render :partial => "color_palette", :locals => { :name => name, :colors => colors }
.extra
  - MapStyles::EXTRA_PALETTES.each do |name, colors|
    = render :partial => "color_palette", :locals => { :name => name, :colors => colors }

app/views/maps/_embed.html.erb
<%- style_class     = nil if local_assigns[:klass].nil? -%>
<%- loading_message = ""  if local_assigns[:loading_message].nil? -%>

<%= content_tag(:div, loading_message, :id => map.dom_token, :class => style_class) %>
<%= javascript_include_tag "#{GeoIQ.base_uri}/javascripts/f1.api.js" %>
<script type="text/javascript" charset="utf-8">
F1.host = <%= geoiq_proxy_url.inspect %>;
var <%= map.dom_token %> = new F1.Maker.Map({
  dom_id: <%= map.dom_token.inspect %>,
  map_id: <%= map.geoiq_map_xid.inspect %>,
  uiLayers: false,
  onload: function() { this.showControl("legend", true, "open"); }
});
</script>

app/views/maps/new.html.haml
- title "Create a Map"
- body_class "form"

.heading
  %h2 Create a Map
  %p.description
    Get started by uploading or pasting your data, selecting the entries you
    want to map, providing a title, and shazam you have an instant map.

= completable_fieldset(@map, :original_csv_data, :class => "import", "data-step" => "Start Here") do
  .upload
    = form_tag preprocess_new_map_path, :class => "preprocess-form" do
      = label_tag "preprocess-upload", "&nbsp".html_safe
      = link_to "javascript:;", :class => "file" do
        Upload Data
        = file_field_tag :data, :id => "preprocess-upload"
    .hint
      Excel or CSV
      = surround("(", ")") do
        = link_to "see examples", page_path("usage", :anchor => "spreadsheets"), :target => "usage"
  .paste
    = form_tag preprocess_new_map_path, :class => "preprocess-form" do
      = label_tag "preprocess-paste", "Copy & Paste Data"
      = text_area_tag :data, "", :id => "preprocess-paste"
    .hint Columns names must be in the first row.
  .or
    .text OR
    = link_to "Undo", "#", :class => "undo", :title => "Undo Data Import"

= form_for @map do |f|
  = f.hidden_field :original_csv_data
  %section.post-process{ :style => (@map.original_csv_data.blank? ? "display: none;" : nil) }
    = completable_fieldset(@map, :location_column_name, :location_column_type, :class => "location required", "data-step" => "Next Step") do
      .inner
        = f.label :location_column_name, "Select Location"
        .detail Please select the column that you want to use for mapping location.
        .input
          Show
          = f.select :location_column_name, [], {}, :class => "column-names required"
          as
          = f.select :location_column_type, location_type_options, {}, :class => "required"
        .hint sample, sample, sample

    = completable_fieldset(@map, :data_column_name, :data_column_type, :class => "data required", "data-step" => "Next Step") do
      .inner
        = f.label :data_column_name, "Select Data"
        .detail Please select the numeric data field that you want to display.
        .input
          Show
          = f.select :data_column_name, [], {}, :class => "column-names required"
          as
          = f.select :data_column_type, data_type_options, {}, :class => "required"
        .hint sample, sample, sample

    = completable_fieldset(@map, :title, :class => "title required", "data-step" => "Customize") do
      .inner
        = f.label :title, "Map Title"
        = f.text_field :title, :class => [(@map.new_record? ? "suggested" : nil), "required"].join(" ")

  .actions
    = f.submit "Create Map"

#pointer{ "data-overlay" => "4" }
  .content Step 1

app/views/maps/show.html.haml
- title    @map.title
- og_url   map_url(@map.token)
- og_image map_cache_url(@map.token, :format => "png")

= div_for @map do
  .header
    .aux
      = render :partial => "add_this"
      .created
        Created:
        = @map.created_at.strftime("%b %d, %Y")
    %h2= link_to @map.title, map_url(@map)
  .map-wrapper
    = compact_embed_code(@map, :style_class => "loading", :loading_message => "Loading...").html_safe
    .controls
      #embed-control.control
        %button Embed
        .dialog
          - embed_code = compact_embed_code(@map)
          %textarea.copyable{ :spellcheck => "false" }= embed_code.html_safe
          = clippy(embed_code, "#DDFDDC")
      #export-control.control
        %button Export
        .dialog
          %ul
            %li.first= link_to "Image", map_path(@map.token, :format => "png"), :class => "png-export"
            %li= link_to "CSV", map_path(@map.token, :format => "csv"), :class => "csv-export"
            %li= link_to "KML", map_path(@map.token, :format => "kml"), :class => "kml-export"
      = map_admin_section(@map) do
        #style-control.control
          %button Map Style
          .dialog= render :partial => "color_palettes"
        #save-control.control
          = form_for @map do |f|
            = f.hidden_field :extent
            = f.hidden_field :color_palette
            = f.hidden_field :flip_colors
            %button{ :type => "submit" } Save Changes

= javascript_tag do
  = "var MAP = #{@map.dom_token};"