config/routes.rb
IssueMap::Application.routes.draw do
  resources :maps do
    new do
      post :preprocess
    end
  end
  match "/map_cache/:id", :to => "maps#cache", :as => :map_cache

  match "/proxy/(*path)", :to => "proxy#proxy", :as => :geoiq_proxy
  match "/pages/:action", :to => "pages", :as => :page
  root :to => "pages#home"

  match "/fitter_happier(/:action)", :to => "fitter_happier", :action => :index
end

app/views/pages/_spreadsheet_templates.html.haml
%ul.spreadsheet-templates
  %li= link_to "Countries", "/templates/countries.csv"
  %li= link_to "USA States", "/templates/usa_states.csv"
  %li= link_to "USA Counties", "/templates/usa_counties.csv"
  %li= link_to "FCC Major Trading Areas", "/templates/fcc_major_trading_areas.csv"
  %li= link_to "FCC Basic Trading Areas", "/templates/fcc_basic_trading_areas.csv"

app/views/pages/_steps.html.haml
%ol.steps
  %li Upload or paste your raw map data...
  %li ...Customize map display, publish online, and share!

app/views/pages/error_404.html.haml
- title "HTTP 404"
.description
  = render :partial => "steps"
  .intro
    %h2 We're sorry.<br />We can't find that.

    %p For some reason, we could not find the page you were looking for. Did you mistype the address? Perhaps, the page moved.

    %p Please send us feedback how the problem occured.

app/views/pages/error_422.html.haml
- title "HTTP 404"
.description
  = render :partial => "steps"
  .intro
    %h2 We're sorry.<br />The change was rejected.

    %p For some reason, we can not process that request. Maybe you tried to change something you didn't have access to.

    %p Please send us feedback how the problem occured.

app/views/pages/error_500.html.haml
- title "HTTP 500"
.description
  = render :partial => "steps"
  .intro
    %h2 We're sorry.<br />We ran into a problem.

    %p For some reason, we had trouble making a map from your data. IssueMap is new to the world and still figuring out the wild array of data, formats, and how to sketch a good map.

    %p Please send us feedback how the problem occured.

app/views/pages/faq.html.haml
- title "FAQ"
:markdown
  ## Frequently Asked Questions

  ### What is this site?

  IssueMap is a project by the FCC and FortiusOne to make it easier for citizens to create their own maps and share them widely. The process is super simple. You just need a spreadsheet or table of data that references a commons geographic boundary and a set of values you would like to map to those boundaries. Follow the simple two step process and you'll have a thematic map you can share across you social networks (Twitter, Facebook, email) and your audience can grab the map as an embed, download an image, grab the map as KML or get the raw data as a .csv.

  ### Why didn’t all of my geographic areas (boundaries) get mapped?

  Check the spelling. IssueMap cannot map geographic areas that are not spelled the same as the list we maintain.  If you are having problems with the boundaries not being mapped because of spelling issues, we suggest you use one of the unique identifier options like ISO code for countries, Area ID for FCC boundaries or FIPS codes for US states and counties.

  ### There is not an option in IssueMap for the geographic areas (boundaries) I would like to map.

  We are looking for additional boundaries to add to IssueMap, so please click the "feedback" button and let us know what boundaries you would like to see in the option list.

  ### I have street addresses and can’t get them mapped in IssueMap.

  IssueMap does not currently geocode street addresses and only joins data to geographic boundaries.  FortiusOne recommends you use one of the popular geocoders and mapping tools available online like [GeoCommons.com](http://geocommons.com/) or [BatchGeo.com](http://batchgeo.com/).

  ### How do featured maps get selected?

  Right now, FortiusOne staff selects featured maps by hand.  In the future, we are looking at automating selection of the most popular maps.

  ### How is the FCC involved in IssueMap?

  IssueMap is the product of partnership between the FCC and FortiusOne. We think it’s a great example of a private/public collaboration done right.  The IssueMap team at FortiusOne shares the FCC’s commitment to unlocking public datasets to help citizens better engage with government data.  Products like IssueMap can also be a key tool for decision-makers, educators, and consumers to better understand how issues impact communities. IssueMap is one part of a larger FCC initiative to revamp how government agencies create value and support citizens.

  ### Will my data be made public?

  Yes, any data uploaded to IssueMap will be in the public domain.  If you have private data that you do not wish to be shared, you should not upload it to IssueMap.

  ### How do I share my map once I’ve created it?

  There are several options for sharing your new map.  1) You can click "export" and have the option to download you map as an image, KML or CSV.  You can embed the image in a document or presentation, the KML will open the map in popular mapping applications like Google Earth and the CSV file makes the data available to be read in spreadsheet programs.  2) You can also choose to click "embed" and click the copy button allowing you to embed that map on another Web page, blog or wiki.  3) You can also share the link to your map by clicking the Twitter, Facebook, or email icons to send it to your social networks.

  ### Can I make the legend go away?

  Yes, just click the green triangle on the legend and it will disappear except for a tab saying "legend."  You can make it reappear by clicking the green triangle in the tab.

app/views/pages/home.html.haml
- content_for :javascripts do
  = javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.min.js"
  = javascript_include_tag "jquery.jcoverflip.js"

- title "Home"
.description
  = render :partial => "steps"

  .intro
    %h2 Got Data?<br />Let us map it for you.

    %p IssueMap joins your data to boundaries so that you can easily create thematic maps and share them online.

    = render :partial => "shared/new_map_call_to_action"

%ul#gallery
  - @maps.each do |map|
    %li
      = link_to map_path(map) do
        = image_tag map_cache_path(map.token, :format => "png"), :alt => map.title

app/views/pages/privacy.html.erb
<% title "Privacy Policy" %>
<h2>Privacy Policy</h2>

<p>IssueMap knows that you care about how your personal information is used and shared, and we take your privacy seriously. Please read the following to learn more about our privacy policy. By accessing IssueMap or using any of the services provided through the Website you are accepting the practices outlined in this Privacy Policy.</p>

<h3>What Does This Privacy Policy Cover?</h3>

<p>This Privacy Policy covers IssueMap’s treatment of personal information that IssueMap gathers when you are on the Websites or any website owned and operated by IssueMap, or when you use the Websites services.
</p>
<p>This Privacy Policy does not apply to content you post or otherwise make available to other users or the public via the website. You acknowledge that any Website display name (if you have one) may be displayed to other users when you post content. Any content that you submit to the Website may be widely redistributed through the Internet and other media channels.
</p>
<p>This policy does not apply to the practices of third parties that IssueMap does not own or control, or to individuals that IssueMap does not employ or manage.
</p>
<h3>Website Visitors</h3>

<p>IssueMap may collect non-personally-identifying information including the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. IssueMap's purpose in collecting non-personally identifying information is to better understand how the Websites' visitors use each site. From time to time, IssueMap may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.
</p>
<h3>Protection of Certain Personally-Identifying Information</h3>

<p>IssueMap discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on IssueMap's behalf or to provide services available at IssueMap's websites and services, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using IssueMap's websites, you consent to the transfer of such information to them. IssueMap will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, IssueMap discloses potentially personally-identifying and personally-identifying information only when required to do so by law, court order, or when IssueMap believes in good faith that disclosure is reasonably necessary to protect the property or rights of IssueMap, third parties or the public at large.
</p>
<h3>Cookies</h3>

<p>A cookie is a string of information that a website stores on a visitor's computer, and that the visitor's browser provides to the website each time the visitor returns. IssueMap uses cookies to help IssueMap identify and track visitors, their usage of the Websites, and their website access preferences. IssueMap visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using IssueMap's websites, with the drawback that certain features of IssueMap's websites may not function properly without the aid of cookies.
</p>
<h3>Privacy Policy Changes</h3>

<p>IssueMap may change its Privacy Policy from time to time, and in IssueMap's sole discretion. IssueMap encourages visitors to frequently check this page for any changes to its Privacy Policy. If changes are made, notice through the website. Your continued use of our sites and services after any change in this Privacy Policy will constitute your acceptance of such change.
</p>
<h3>Questions?</h3>

<p>IssueMap's full contact information, including location, may be found on our <a href="http://fortiusone.com/Contact-Us" title="Contact FortiusOne" rel="me">Contact</a> page.
</p>
<h3>Creative Commons</h3>

<p>This Privacy Policy document is derived from the privacy policy published by Swivel and is licensed under a <a href="http://creativecommons.org/licenses/by-sa/2.5/" title="Creative Commons &mdash;
      Attribution-ShareAlike 2.5 Generic">Creative Commons Attribution-ShareAlike 2.5 License</a>.
</p>

app/views/pages/usage.html.haml
- title "Usage"
:markdown
  ## How to Use

  ### Step 1: Copy {#step1}

  Using IssueMap is as simple as "copy, paste, map." To create a map, first find a spreadsheet or well-formatted table that you want to map. IssueMap supports imports as .CSV, .XLS, .XLSX, or .ODF.  Alternatively, you can copy your data from a spreadsheet, or a table from the Web or other digital documents, and paste it into the IssueMap text box.

  IssueMap works best with data that is cleanly-formatted. The top row of the data should have the attributes for the data and the rows beneath should have the values or text for each attribute. At least one of the attributes needs to be a reference to a geographic boundary (like state, country, zipcode etc.).

  ### Step 2: Paste {#step2}

  Joining your data with geographic boundaries is easy. Select the appropriate geographic boundary for your data from a list provided by IssueMap, then indicate what value from the data you would like to map. Then, tell IssueMap what kind of data you’re dealing with: text (words), whole numbers, decimals, or time/date. Finally, give your map a title and click "Create Map."

  ### Step 3: Map {#step3}

  Now that your map has been created, you have several options to share it.  Click "export" to download your map. Select "image" to use the map in a document or presentation; "KML" to open the map in popular mapping applications like Google Earth; and "CSV" to make the data available to be read in spreadsheet programs. You can also choose to easily embed the IssueMap product on another Web page, blog or wiki  with pre-populated embed code. Finally, IssueMap makes it easy to share your map by clicking the Twitter, Facebook, or email icons to send it to your social networks.

  ### Example Spreadsheets {#spreadsheets}

= render :partial => "spreadsheet_templates"